name: 🚀 Deploy website on push (Main)

on:
  push:
    branches:
      - main
jobs:
  deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
          extensions: mbstring, bcmath, intl, pdo, tokenizer, xml
          tools: composer

      - name: Cache Composer packages
        id: composer-cache
        uses: actions/cache@v4.2.0
        with:
          path: vendor
          key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-php-

      - name: Install Composer Dependencies
        run: composer install --no-dev --no-interaction --prefer-dist --optimize-autoloader

      - name: Install Node.js and Build Assets
        uses: actions/setup-node@v3
        with:
          node-version: '23'
      - run: npm ci
      - run: npm install
      - run: npm run build

      - name: Set up SSH key
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY_DEPLOY }}
          ssh-passphrase: ${{ secrets.SSH_PRIVATE_KEY_DEPLOY_PASSPHRASE }}

      - name: Sync files via SSH
        run: |
        rsync -avz --delete --exclude '.env' --exclude=".git" --exclude="node_modules" -e "ssh -o StrictHostKeyChecking=no" ./ ${{ SSH_USER}}@${{ SSH_HOST }}:${{ WEB_DIR }}

      - name: Trigger Laravel Optimization Commands
        run: |
          curl -X POST ${{ secrets.DOMAIN }} \
          -d "key=${{ secrets.DEPLOY_KEY }}"

